#!/bin/sh
MAILTO=""
LAB_REPO_HOST=${LAB_REPO_HOST:-"hub.docker.com"}
LAB_REPO_OWNER=${LAB_REPO_OWNER:-"lsstsqre"}
LAB_REPO_NAME=${LAB_REPO_NAME:-"jld-lab"}
RANDOM_DELAY=30 # So they don't all run at once.
export RANDOM_DELAY
if [ -n "${LAB_IMAGE}" ]; then
    LAB_CONTAINER_NAMES="${LAB_IMAGE}"
    echo "Pulling image ${LAB_IMAGE}"
else
    echo "Pulling image ${LAB_REPO_OWNER}:${LAB_REPO_NAME}from ${LAB_REPO_HOST}!"
    get_builds -r ${LAB_REPO_HOST} \
	       -o ${LAB_REPO_OWNER} \
	       -n ${LAB_REPO_NAME} \
	       > /tmp/jld-lab.env
    . /tmp/jld-lab.env
    rm /tmp/jld-lab.env
fi
if [ -z "${JLD_INFRASTRUCTURE_IMAGES}" ]; then
    JLD_INFRASTRUCTURE_IMAGES="lsstsqre/jld-hub"
fi
IMAGES=$(echo ${LAB_CONTAINER_NAMES} ${JLD_INFRASTRUCTURE_IMAGES} | \
          tr ',' ' ')
for i in ${IMAGES}; do
    docker pull ${i}
done
docker rmi $(docker images --quiet --filter "dangling=true")
