#!/usr/bin/env bash
r="/usr/local/bin/workflow-rest"

args=""

if [ -n "${WF_API_PORT}" ]; then
    args="${args} -p ${WF_API_PORT}"
fi
if [ -n "${WF_API_ADDR}" ]; then
    args="${args} -b ${WF_API_ADDR}"
fi
if [ -n "${WF_MOCK_AUTHENTICATION}" ]; then
    args="${args} -m"
fi
if [ -n "${WF_NO_VERIFY_SIGNATURE}" ]; then
    args="${args} --no-verify-signature"
fi
if [ -n "${WF_NO_VERIFY_AUDIENCE}" ]; then
    args="${args} --no-verify-audience"
fi

exec ${r} ${args}
