#!/bin/bash

set -e

DRY_RUN=false
PYVER=3
KFILE=lsst_kernel_py${PYVER}.json

usage() {
    echo 1>&2 "Usage: $0 [-d] TAG"
    exit 2
}

OPTIND=1
while getopts dh: opt; do
    case $opt in
        d)
            DRY_RUN=true
            ;;
        h)
            usage
            ;;
    esac
done
shift "$((OPTIND-1))"

TAG=$1
VERSION=${TAG//_/}
VERSION=${VERSION/#v/r}


if [[ -z $TAG ]] || [[ $# -gt 1 ]]; then
    usage
fi

sed -e "s/{{PYVER}}/${PYVER}/g" lsst_kernel.json.template > ${KFILE}

sed -e "s|{{TAG}}|${TAG}|g; s|{{VERSION}}|${VERSION}|g; s|{{PYVER}}|${PYVER}|g"\
    Dockerfile.template > Dockerfile

if [[ $DRY_RUN != true ]]; then
    ./bld_1
fi
