RUN  groupadd -g 768 jupyter && chgrp -R jupyter /opt/lsst && \
      chmod -R g+w /opt/lsst
RUN  yum install -y epel-release
RUN  yum repolist
RUN  yum -y upgrade
# Manual http-parser installation needed for newer nodejs, until CentOS 7.4
#  is released.
RUN  rpm -ivh https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm
RUN  yum -y install python-pip python34 python34-pip gcc python34-devel \
      git \
      python-devel nodejs \
      pandoc \
      texlive texlive-collection-xetex texlive-ec texlive-upquote \
      texlive-adjustbox \
      make zlib-devel perl-ExtUtils-MakeMaker gettext
# Newer git; install to /usr/local/bin
RUN  V="2.9.5" && \
     D="git-${V}" && \
     FN="${D}.tar.gz" && \
     mkdir -p /usr/local/src && \
     cd /usr/local/src && \
     curl -L https://www.kernel.org/pub/software/scm/git/${FN} -o ${FN} && \
     tar xvfz ${FN} && \
     cd ${D} && \
     ./configure --without-tcltk && \
     make && \
     make install
RUN  cd /tmp && \
     V="2.2.9" && \
     FN="hub-linux-amd64-${V}" && \
     F="${FN}.tgz" && \
     URL="https://github.com/github/hub/releases/download/v${V}/${F}" && \
     cmd="curl -L ${URL} -o ${F}" && \
     $cmd && \
     tar xpfz ${F} && \
     install -m 0755 ${FN}/bin/hub /usr/bin && \
     rm -rf ${F} ${FN}
RUN  pip3 install --upgrade pip setuptools
RUN  pip2 install --upgrade pip setuptools
RUN  pip3 install --upgrade virtualenv virtualenvwrapper \
      ipykernel \
      nbdime \
      pandoc
# Now do weird snowflake versions of things, and order matters.
RUN   pip3 install \
      https://github.com/jupyter/notebook/zipball/master       \
      https://github.com/jupyterlab/jupyterlab/zipball/d47a2c1d9f2ee4063aeddf9b3c5fc536b3ff1a08  \
      https://github.com/jupyterhub/jupyterhub/zipball/master  \
     'sqre-labkubespawner>=0.0.8'
RUN  git ls-remote https://github.com/jupyterlab/jupyterlab.git master | \
       awk '{print $1}' > /root/jupyterlab.commit
RUN  pip2 install --upgrade virtualenv virtualenvwrapper
# We need notebook from master to get the equivalent of --allow-root
RUN  python3 /usr/bin/nbdime config-git --enable --system
RUN  source /opt/lsst/software/stack/loadLSST.bash && \
      pip install --upgrade pip && \
      pip install ipykernel
