RUN  groupadd -g 768 jupyter && chgrp -R jupyter /opt/lsst && \
      chmod -R g+w /opt/lsst
RUN  yum install -y epel-release
RUN  yum repolist
RUN  yum -y upgrade
RUN  yum -y install python-pip python34 python34-pip gcc python34-devel \
      python-devel nodejs npm git
RUN  cd /tmp && \
     V="2.2.9" && \
     FN="hub-linux-amd64-${V}" && \
     F="${FN}.tgz" && \
     URL="https://github.com/github/hub/releases/download/v${V}/${F}" && \
     cmd="curl -L ${URL} -o ${F}" && \
     $cmd && \
     tar xpfz ${F} && \
     install -m 0755 ${FN}/bin/hub /usr/bin && \
     rm -rf ${F} ${FN}
RUN  pip3 install --upgrade pip setuptools
RUN  pip2 install --upgrade pip setuptools
RUN  pip3 install --upgrade virtualenv virtualenvwrapper ipykernel nbdime \
      sqre-labkubespawner jupyterlab
RUN  pip2 install --upgrade virtualenv virtualenvwrapper
# We need local notebook to get the equivalent of --allow-root
COPY assets/notebook-5.1.0.dev0-py2.py3-none-any.whl \
       /tmp/
RUN  pip3 install \
       /tmp/notebook-5.1.0.dev0-py2.py3-none-any.whl
RUN  python3 /usr/bin/nbdime config-git --enable --system
RUN  source /opt/lsst/software/stack/loadLSST.bash && \
      pip install --upgrade pip && \
      pip install ipykernel \
       /tmp/notebook-5.1.0.dev0-py2.py3-none-any.whl
