RUN  groupadd -g 768 jupyter && chgrp -R jupyter /opt/lsst && \
      chmod -R g+w /opt/lsst
RUN  yum install -y epel-release
RUN  yum repolist
RUN  yum -y upgrade
RUN  yum -y install python-pip python34 python34-pip gcc python34-devel \
      python-devel nodejs git \
      texlive texlive-collection-xetex texlive-ec texlive-upquote \
      texlive-adjustbox
RUN  cd /tmp && \
     V="2.2.9" && \
     FN="hub-linux-amd64-${V}" && \
     F="${FN}.tgz" && \
     URL="https://github.com/github/hub/releases/download/v${V}/${F}" && \
     cmd="curl -L ${URL} -o ${F}" && \
     $cmd && \
     tar xpfz ${F} && \
     install -m 0755 ${FN}/bin/hub /usr/bin && \
     rm -rf ${F} ${FN}
RUN  pip3 install --upgrade pip setuptools
RUN  pip2 install --upgrade pip setuptools
RUN  pip3 install --upgrade virtualenv virtualenvwrapper \
      ipykernel \
      nbdime pandoc
# Now do weird snowflake versions of things, and order matters.
#       https://github.com/jupyterlab/jupyterlab/zipball/13b074667221ce922ed7b6baa9f4d37045c155aa \
RUN   pip3 install \
      https://github.com/jupyter/notebook/zipball/master \
      https://github.com/blink1073/jupyterlab/zipball/should_build_sudo \
      https://github.com/jupyterhub/jupyterhub/zipball/master \
     'sqre-labkubespawner>=0.0.8'
RUN  pip2 install --upgrade virtualenv virtualenvwrapper
# We need notebook from master to get the equivalent of --allow-root
RUN  python3 /usr/bin/nbdime config-git --enable --system
RUN  source /opt/lsst/software/stack/loadLSST.bash && \
      pip install --upgrade pip && \
      pip install ipykernel
