apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: proxy
    selector:
      matchLabels:
        app: proxy
    spec:
      serviceAccountName: hub
      containers:
        - name: hub
          imagePullPolicy: "Always"
          image: "jupyterhub/configurable-http-proxy"
          command:
            - configurable-http-proxy
            - --ip=0.0.0.0
            - --api-ip=0.0.0.0
            - --api-port=8001
            - --default-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT_API)
            - --error-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT_API)/hub/error
            - --port=8000
          env:
            - name: CONFIGPROXY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hub
                  key: configproxy_auth_token
            - name: NODE_OPTIONS
              value: "--max-http-header-size={{MAX_HTTP_HEADER_SIZE}}"
              # This needs to be 16K or more for JWT.  Value is in bytes.
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: api
