kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # Cluster roles not namespaced
  name: {{ template "nublado.fullname" . }}-prepuller
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
