apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstashrmq
  labels:
    app: logstashrmq
spec:
  template:
    metadata:
      labels:
        name: logstashrmq
    selector:
      matchLabels:
        app: logstashrmq
    spec:
      containers:
        - name: logstashrmq
          imagePullPolicy: "Always"
          image: "lsstsqre/logstash-rabbitmq-shovel"
          env:
            - name: RABBITMQ_TARGET_HOST
              value: '{{RABBITMQ_TARGET_HOST}}'
            - name: RABBITMQ_TARGET_VHOST
              value: '{{RABBITMQ_TARGET_VHOST}}'
            - name: RABBITMQ_PAN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstashrmq
                  key: rabbitmq.pan.password
