# Iterate over the list of mounts in the values
# and make a document like this for each of them.
# The reason for the template with the . is that
# is the currently iterated item.
{{ $volume_size := .Values.fileserver.shared_volume_size }}
{{ $name := include "nublado.fullname" . }}
{{ $namespace := .Release.Namespace }}
{{- range .Values.fileserver.mounts }}

apiVersion: v1
kind: PersistentVolume
metadata:
  # PersistentVolumes are not namespaced, so you need to have an
  #  identifier in the name
  name: {{ $name }}-{{ . }}
  # Needed (but dangerous) to keep the notebook from freezing.
  annotations:
    volume.beta.kubernetes.io/mount-options: "local_lock=all"
spec:
  capacity:
    # Must be a little smaller than the actual PV.
    storage: {{ $volume_size }}
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  nfs:
    server: '{{ $name }}-fileserver.{{ $namespace }}.svc.cluster.local'
    path: "/exports/{{ . }}"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $name }}-{{ . }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ $volume_size }}
  storageClassName: fast

---
{{- end }}
