apiVersion: v1
kind: Service
metadata:
  name: {{ template "nublado.fullname" . }}-fileserver
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    name: {{ template "nublado.fullname" . }}-fileserver
