kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{CLUSTER_IDENTIFIER}}
  name: dask
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
