kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dask
subjects:
- kind: ServiceAccount
  name: dask
  namespace: {{CLUSTER_IDENTIFIER}}
roleRef:
  kind: Role
  name: dask
  apiGroup: rbac.authorization.k8s.io

