kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nublado.fullname" . }}-hub
subjects:
- kind: ServiceAccount
  name: {{ template "nublado.fullname" . }}-hub
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "nublado.fullname" . }}-hub
  apiGroup: rbac.authorization.k8s.io
