apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nublado.fullname" . }}-hub-config
data:
  {{ $root := . }}
  jupyterhub_config.py: |-
    {{ $root.Files.Get "static/jupyterhub_config.py" | trimSuffix "\n" | nindent 4 }}

  {{- (.Files.Glob "static/jupyterhub_config.d/*").AsConfig | nindent 2 }}
