kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nublado.fullname" . }}-hub
rules:
- apiGroups: [""]
  resources: ["pods","events"]
  verbs: ["get", "list", "create", "watch", "delete"]
