apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nublado.fullname" . }}-hub
type: Opaque
stringData:
  oauth_client_id: '{{ .Values.oauth_client_id}}'
  oauth_secret: '{{.Values.oauth_secret}}'
  oauth_callback_url: '{{.Values.scheme}}{{.Values.fqdn}}{{.Values.routes.hub}}/hub/oauth_callback'
  github_organization_whitelist: '{{.Values.github_organization_whitelist}}'
  github_organization_denylist: '{{.Values.github_organization_denylist}}'
  cilogon_group_whitelist: '{{.Values.cilogon_group_whitelist}}'
  cilogon_group_denylist: '{{.Values.cilogon_group_denylist}}'
  session_db_url: '{{.Values.session_db_url}}'
  {{- if .Values.hub.crypto_key }}
  jupyterhub_crypto_key: '{{.Values.hub.crypto_key}}'
  {{- else }}
  jupyterhub_crypto_key: '{{ randAlphaNum 32 | b64enc }}'
  {{- end }}

  {{- if .Values.hub.proxy_auth_token }}
  configproxy_auth_token: '{{.Values.hub.proxy_auth_token}}'
  {{- else }}
  configproxy_auth_token: '{{randAlphaNum 32 | b64enc }}:{{randAlphaNum 32 | b64enc }}'
  {{- end }}
