apiVersion: v1
kind: Service
metadata:
  name: {{ template "nublado.fullname" . }}-hub
  labels:
    name: {{ template "nublado.fullname" . }}-hub
spec:
  type: NodePort
  ports:
  - name: api
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    name: {{ template "nublado.fullname" . }}-hub
