apiVersion: v1
kind: Service
metadata:
  name: {{ template "nublado.fullname" . }}-proxy
  labels:
    name: {{ template "nublado.fullname" . }}-proxy
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: api
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    name: {{ template "nublado.fullname" . }}-proxy
