#!/bin/bash
for i in jupyter_notebook_config.json lablauncher.bash \
				      local01-virtualenvwrapper.sh \
				      local02-hub.sh local03-showmotd.sh \
				      lsstlaunch.bash \
				      motd \
				      Dockerfile.common.top \
				      Dockerfile.common.bottom \
 				      handlers.py.monkeypatched \
 				      20_jupytervars \
				      runlab.sh ; do
    cp ../jupyterlab/$i .
done
#cp ../../notebook/dist/notebook-5.1.0.dev0-py2.py3-none-any.whl \
#   ../../jupyterhub/dist/jupyterhub-0.8.0.dev0-py3-none-any.whl \
#   ../../sqre-labkubespawner/dist/sqre_labkubespawner-0.0.7-py3-none-any.whl \
#   assets/
#   ../../jupyterlab/dist/jupyterlab-0.24.1-py2.py3-none-any.whl \
YEAR=$1
WEEK=$2
PYVER=3
if [ -n "$3" ]; then
    PYVER=$3
fi
if [ -z "${YEAR}" ] || [ -z "${WEEK}" ]; then
    echo 1>&2 "Usage: $0 year week"
    exit 2
fi
echo "FROM lsstsqre/stacktest:7-stack-lsst_distrib-w_${YEAR}_${WEEK}" > Dockerfile
echo "USER root" >> Dockerfile
cat Dockerfile.common.top >> Dockerfile
echo "ENV   PYVER=${PYVER}" >> Dockerfile
cat Dockerfile.common.bottom >> Dockerfile
desc="JupyterLab demo: LSST Stack (Python ${PYVER})"
echo "LABEL description=\"${desc}\" \\" >> Dockerfile
echo "       name=\"lsstsqre/jld-lab-w${YEAR}${WEEK}\" \\" >> Dockerfile
echo "       version=\"0.${YEAR}.${WEEK}\"" >> Dockerfile
./bld_1

