#!/bin/bash
for i in jupyter_notebook_config.json lablauncher.bash \
				      local01-virtualenvwrapper.sh \
				      local02-hub.sh local03-showmotd.sh \
				      lsstlaunch.bash \
				      motd \
				      Dockerfile.common.top \
				      Dockerfile.common.bottom \
				      runlab.sh ; do
    cp ../jupyterlab/$i .
done
cp ../../notebook/dist/notebook-5.0.0.dev0-py2.py3-none-any.whl \
   assets/
cat Dockerfile.py3.top Dockerfile.common.top Dockerfile.py3.mid \
     Dockerfile.common.bottom Dockerfile.py3.bottom > Dockerfile
./bld_1

