#!/bin/bash
for i in jupyter_notebook_config.json lablauncher.bash \
				      local01-virtualenvwrapper.sh \
				      local02-hub.sh local03-showmotd.sh \
				      lsstlaunch.bash \
				      motd \
				      Dockerfile.common.top \
				      Dockerfile.common.bottom \
				      handlers.py.monkeypatched \
				      20_jupytervars \
				      runlab.sh ; do
    cp ../jupyterlab/$i .
done
cp ../../notebook/dist/notebook-5.1.0.dev0-py2.py3-none-any.whl \
   ../../jupyterlab/dist/jupyterlab-0.24.1-py2.py3-none-any.whl \
   assets/
cat Dockerfile.py2.top Dockerfile.common.top Dockerfile.py2.mid \
     Dockerfile.common.bottom Dockerfile.py2.bottom > Dockerfile
./bld_1
