#!/bin/bash
./bld_1 || exit 2
kubectl delete deployment jld-hub
kubectl create -f kubernetes/jld-hub-deployment.yml
POD=$(kubectl get pods | grep jld-hub | grep Creating | awk '{print $1}')
while : ;do
    kubectl logs -f $POD
    sleep 10
done
