#!/bin/bash
cp ../../sqre-jupyterhub/dist/jupyterhub-0.8.0.dev0-py3-none-any.whl \
    ../../sqre-kubespawner/dist/sqrekubespawner-0.0.8dev0-py2.py3-none-any.whl \
    assets/
./bld_1
kubectl delete deployment jld-hub
kubectl create -f kubernetes/jld-hub-deployment.yml
POD=$(kubectl get pods | grep Creating | awk '{print $1}')
while : ;do
    kubectl logs -f $POD
    sleep 10
done
