#!/bin/sh
if [ -z "${DEPYAMLTPL}" ]; then
    DEPYAMLTPL="kubernetes/deployment.template.yml"
fi
DEPYAML="kubernetes/deployment.yml"
OAUTH_PROVIDER=${OAUTH_PROVIDER:-"github"}
FQDN=${FQDN}:-""}
LAB_SELECTOR_TITLE=${LAB_SELECTOR_TITLE:-"LSST Stack Selector"}
LAB_REPO_HOST=${LAB_REPO_HOST:-"hub.docker.com"}
LAB_REPO_OWNER=${LAB_REPO_OWNER:-"lsstsqre"}
LAB_REPO_NAME=${LAB_REPO_NAME:-"sciplat-lab"}
PREPULLER_EXPERIMENTALS=${PREPULLER_EXPERIMENTALS:-"0"}
PREPULLER_DAILIES=${PREPULLER_DAILIESS:-"3"}
PREPULLER_WEEKLIES=${PREPULLER_WEEKLIES:-"2"}
PREPULLER_RELEASES=${PREPULLER_RELESES:-"1"}
LAB_IDLE_TIMEOUT=${LAB_IDLE_TIMEOUT:-"43200"}
LAB_MEM_GUARANTEE=${LAB_MEM_GUARANTEE:-"512M"}
LAB_CPU_GUARANTEE=${LAB_CPU_GUARANTEE:-"0.5"}
LAB_MEM_LIMIT=${LAB_MEM_LIMIT:-"2G"}
LAB_CPU_LIMIT=${LAB_CPU_LIMIT:-"2.0"}
LAB_SIZE_RANGE=${LAB_SIZE_RANGE:-"4.0"}
LAB_NODEJS_MAX_MEM=${LAB_NODEJS_MAX_MEM:-"8192"}
MB_PER_CPU=${MB_PER_CPU:-"2048"}
TINY_CPU_MAX=${TINY_CPU_MAX:-"0.5"}
HUB_ROUTE=${HUB_ROUTE:-"/nb"}
FIREFLY_ROUTE=${FIREFLY_ROUTE:-"/firefly"}
JS9_ROUTE=${JS9_ROUTE:-"/js9"}
AUTO_REPO_URLS=${AUTO_REPO_URLS:-""}
SIZE_INDEX=${SIZE_INDEX:-"1"}
ALLOW_DASK_SPAWN=${ALLOW_DASK_SPAWN:-""}
MAX_DASK_WORKERS=${MAX_DASK_WORKERS:-""}
RESTRICT_LAB_NODES=${RESTRICT_LAB_NODES:-""}
RESTRICT_DASK_NODES=${RESTRICT_DASK_NODES:-""}
EXTERNAL_FILESERVER_IP=${EXTERNAL_FILESERVER_IP:-""}
EXTERNAL_INSTANCE_URL=${EXTERNAL_INSTANCE_URL:-"https://${FQDN}"}
EXTERNAL_FIREFLY_URL=${EXTERNAL_FIREFLY_URL:-""}
EXTERNAL_API_URL=${EXTERNAL_API_URL:-""}
EXTERNAL_SODA_URL=${EXTERNAL_SODA_URL:-""}
EXTERNAL_HUB_URL=${EXTERNAL_HUB_URL:-""}
if [ -z "${DB_IDENTIFIER}" ]; then
    if [ -z "${GKE_PROJECT}" ]; then
       GKE_PROJECT=$(gcloud config list core/project --format json | \
                         jq -r .core.project)
    fi
    if [ -z "${GKE_REGION}" ]; then
        GKE_REGION=$(gcloud config list compute/region --format json | \
                         jq -r .compute.region)
    fi
    if [ -z "${K8S_NAMESPACE}" ]; then
        K8S_NAMESPACE=$(kubectl config get-contexts \
                            $(kubectl config current-context) \
                            | grep '^*' | awk '{print $NF}')
    fi
    DB_IDENTIFIER="${GKE_PROJECT}:${GKE_REGION}:${K8S_NAMESPACE}"
fi

sed -e "s/{{DEBUG}}/${DEBUG}/g" \
    -e "s/{{OAUTH_PROVIDER}}/${OAUTH_PROVIDER}/g" \
    -e "s/{{FQDN}}/${FQDN}/g" \
    -e "s/{{ALLOW_DASK_SPAWN}}/${ALLOW_DASK_SPAWN}/g" \
    -e "s/{{MAX_DASK_WORKERS}}/${MAX_DASK_WORKERS}/g" \
    -e "s/{{LAB_IMAGE}}/${LAB_IMAGE}/g" \
    -e "s/{{LAB_SELECTOR_TITLE}}/${LAB_SELECTOR_TITLE}/g" \
    -e "s/{{LAB_REPO_HOST}}/${LAB_REPO_HOST}/g" \
    -e "s/{{LAB_REPO_OWNER}}/${LAB_REPO_OWNER}/g" \
    -e "s/{{LAB_REPO_NAME}}/${LAB_REPO_NAME}/g" \
    -e "s/{{PREPULLER_EXPERIMENTALS}}/${PREPULLER_EXPERIMENTALS}/g" \
    -e "s/{{PREPULLER_DAILIES}}/${PREPULLER_DAILIES}/g" \
    -e "s/{{PREPULLER_WEEKLIES}}/${PREPULLER_WEEKLIES}/g" \
    -e "s/{{PREPULLER_RELEASES}}/${PREPULLER_RELEASES}/g" \
    -e "s/{{LAB_IDLE_TIMEOUT}}/${LAB_IDLE_TIMEOUT}/g" \
    -e "s/{{LAB_MEM_LIMIT}}/${LAB_MEM_LIMIT}/g" \
    -e "s/{{LAB_CPU_LIMIT}}/${LAB_CPU_LIMIT}/g" \
    -e "s/{{LAB_MEM_GUARANTEE}}/${LAB_MEM_GUARANTEE}/g" \
    -e "s/{{LAB_CPU_GUARANTEE}}/${LAB_CPU_GUARANTEE}/g" \
    -e "s/{{LAB_SIZE_RANGE}}/${LAB_SIZE_RANGE}/g" \
    -e "s/{{LAB_NODEJS_MAX_MEM}}/${LAB_NODEJS_MAX_MEM}/g" \
    -e "s/{{MB_PER_CPU}}/${MB_PER_CPU}/g" \
    -e "s/{{TINY_CPU_MAX}}/${TINY_CPU_MAX}/g" \
    -e "s/{{AUTO_REPO_URLS}}/${AUTO_REPO_URLS}/g" \
    -e "s/{{DB_IDENTIFIER}}/${DB_IDENTIFIER}/g" \
    -e "s|{{HUB_ROUTE}}|${HUB_ROUTE}|g" \
    -e "s|{{FIREFLY_ROUTE}}|${FIREFLY_ROUTE}|g" \
    -e "s|{{JS9_ROUTE}}|${JS9_ROUTE}|g" \
    -e "s/{{SIZE_INDEX}}/${SIZE_INDEX}/g" \
    -e "s/{{RESTRICT_DASK_NODES}}/${RESTRICT_DASK_NODES}/g" \
    -e "s/{{RESTRICT_LAB_NODES}}/${RESTRICT_LAB_NODES}/g" \
    -e "s/{{EXTERNAL_FILESERVER_IP}}/${EXTERNAL_FILESERVER_IP}/g" \
    -e "s/{{EXTERNAL_INSTANCE_URL}}/${EXTERNAL_INSTANCE_URL}/g" \
    -e "s/{{EXTERNAL_FIREFLY_URL}}/${EXTERNAL_FIREFLY_URL}/g" \
    -e "s/{{EXTERNAL_SODA_URL}}/${EXTERNAL_SODA_URL}/g" \
    -e "s/{{EXTERNAL_API_URL}}/${EXTERNAL_API_URL}/g" \
    -e "s/{{EXTERNAL_HUB_URL}}/${EXTERNAL_HUB_URL}/g" \
    ${DEPYAMLTPL} > ${DEPYAML}
