#!/bin/bash
if [ -x ./get_builds ]; then
    ./get_builds > ./jld-lab.env.sh
fi
if [ -f ./jld-lab.env.sh ]; then
    . ./jld-lab.env.sh
fi
if [ -z "${LAB_CONTAINER_NAMES}" ]; then
    export LAB_CONTAINER_NAMES="jld-lab:latest"
    export LAB_CONTAINER_DESCS="Latest"
fi
export DEPYAML="kubernetes/jld-hub-deployment.yml"
sed -e "s|{{LAB_CONTAINER_NAMES}}|\"${LAB_CONTAINER_NAMES}\"|" \
    -e "s|{{LAB_CONTAINER_DESCS}}|\"${LAB_CONTAINER_DESCS}\"|" \
    ${DEPYAML}.template > ${DEPYAML}
